var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/[...nextauth]/route.js")
R.c("server/chunks/node_modules_next_05fqyxl._.js")
R.c("server/chunks/node_modules_@opentelemetry_api_build_esm_0ltshjr._.js")
R.c("server/chunks/node_modules_@auth_core_0mqqeto._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_0tf8be1._.js")
R.c("server/chunks/node_modules_0v7-_76._.js")
R.c("server/chunks/[root-of-the-server]__0b_122q._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_[___nextauth]_route_actions_04_0y9h.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/[...nextauth]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/auth/[...nextauth]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
